#!/bin/sh

set -e
case "$1" in

    purge|configure|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    upgrade)
    if [ -f /usr/bin/weavedstart.sh ]; then
	usr/bin/weavedstart.sh    
    fi
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

echo "================================================================================"
echo
echo "Run sudo weavedinstaller to interactively add Weaved remote connection services."
echo
echo "================================================================================"
echo "If you are adding Weaved to a mass produced product:"
echo "Copy and edit /usr/bin/weavedinstaller_OEM to add account credentials"
echo "and definitions of services you wish to install."
echo "Run sudo weavedinstaller_OEM to add Weaved remote connection services."
echo "See additional information in the weavedinstaller_OEM script."
echo
