#!/bin/sh
# postrm script for weavedconnectd
#

set -e
logger "prerm $1"

case "$1" in

    remove|upgrade|failed-upgrade|deconfigure)
  ;;

    upgrade)
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

exit 0

