#!/bin/sh
# prerm script for weavedconnectd
#

set -e
logger "weavedconnectd 1.3-07j installer prerm $1"

case "$1" in

    remove|purge|deconfigure)
# remove serial number (HWID) file
    if [ -e /etc/weaved/serial.txt ]; then
      rm /etc/weaved/serial.txt
    fi
# remove configured and active enablement files
for f in /etc/weaved/active/*.i686; do

    ## Check if the glob gets expanded to existing files.
    ## If not, f here will be exactly the pattern above
    ## and the exists test will evaluate to false.
    [ -e "$f" ] && echo "files do exist" || echo "files do not exist"

    ## This is all we needed to know, so we can break after the first iteration
    break
    rm /etc/weaved/active/*.i686
done

#    if [ -e /etc/weaved/active/*.i686 ]; then
#      rm /etc/weaved/active/*.i686
#    fi

# remove configured enablement files
for f in /etc/weaved/available/*.i686; do

    ## Check if the glob gets expanded to existing files.
    ## If not, f here will be exactly the pattern above
    ## and the exists test will evaluate to false.
    [ -e "$f" ] && echo "files do exist" || echo "files do not exist"

    ## This is all we needed to know, so we can break after the first iteration
    break
    rm /etc/weaved/available/*.i686
done

#    if [ -e /etc/weaved/available/*.i686 ]; then
#      rm /etc/weaved/available/*.i686
#    fi
    weavedstop.sh
  ;;

    upgrade|failed-upgrade)
  ;;

  *)
    logger "weavedconnectd prerm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

exit 0

