#!/bin/sh
# prerm script for weavedconnectd
#

set -e
logger "weavedconnectd 1.3-07 installer prerm $1"

case "$1" in

    remove|purge|deconfigure)
# remove serial number (HWID) file
    if [ -e /etc/weaved/serial.txt ]; then
      rm /etc/weaved/serial.txt
    fi
# remove configured and active enablement files
    if [ -e /etc/weaved/active/*.i686 ]; then
      rm /etc/weaved/active/*.i686
    fi
# remove configured enablement files
    if [ -e /etc/weaved/available/*.i686 ]; then
      rm /etc/weaved/available/*.i686
    fi
    weavedstop.sh
  ;;

    upgrade|failed-upgrade)
  ;;

    upgrade)
  ;;

  *)
    logger "weavedconnectd prerm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

exit 0

