#!/bin/sh
# postrm script for weavedconnectd
#

platform=i686
set -e

case "$1" in

    remove|upgrade|failed-upgrade|deconfigure)
    weavedRunning=$(ps ax | grep weavedconnectd | grep -v grep) || true	
#    echo "weavedRunning=$weavedRunning"
    if [ "$weavedRunning" != "" ]; then
	killall weavedconnectd.$platform   
    fi
    schannelRunning=$(ps ax | grep schannel | grep -v grep) || true	
#    echo "schannelRunning=$schannelRunning"
    if [ "$schannelRunning" != "" ]; then
	killall schannel.$platform   
    fi
  ;;

    upgrade)
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

exit 0

