#!/bin/sh
# postrm script for remot3it
#

set -e
logger "remot3it installer prerm $1"

case "$1" in

    remove|purge|deconfigure)
# remove serial number (HWID) file
    if [ -e /etc/remot3it/serial.txt ]; then
      rm /etc/remot3it/serial.txt
    fi
  ;;

    upgrade|failed-upgrade)
  ;;

    upgrade)
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

exit 0

