#!/bin/sh
# Weaved services installer for Netcomm
# needs to be run as root
#
#config
WEAVED_DIR="/etc/weaved"
PROVISION_DEFAULT="$WEAVED_DIR/pfiles"
DEVICES_ACTIVE="$WEAVED_DIR/active"
DEVICES_AVAILABLE="$WEAVED_DIR/available"
#
# create and directories needed
#
mkdir $WEAVED_DIR                             
mkdir $PROVISION_DEFAULT
mkdir $DEVICES_ACTIVE
mkdir $DEVICES_AVAILABLE

#
# install bins
#
cp weavedConnectd.arm-gnueabi-shared /usr/bin/weavedconnectd
chmod +x /usr/bin/weavedconnectd
cp schannel.arm-gnueabi /usr/bin/schannel
chmod +x /usr/bin/schannel
cp task_notify.sh /usr/bin/task_notify.sh
chmod +x /usr/bin/task_notify.sh
cp weavedregister_net /usr/bin/weavedregister_net
chmod +x /usr/bin/weavedregister_net
cp weavedsimplelib /usr/bin/weavedsimplelib

#
# Check for existing files, dont overwrite
#
cp enablements/ssh.netcomm $PROVISION_DEFAULT
cp enablements/rmt3.netcomm $PROVISION_DEFAULT 
cp enablements/web.netcomm $PROVISION_DEFAULT 
cp enablements/schannel.conf $WEAVED_DIR 

# copy startup scripts
cp weavedSSH /etc/init.d/rc.d
cp weavedRMT3 /etc/init.d/rc.d
cp weavedWEB /etc/init.d/rc.d
cp weavedSCH /etc/init.d/rc.d
#
chmod +x /etc/init.d/rc.d/weavedSSH
chmod +x /etc/init.d/rc.d/weavedRMT3
chmod +x /etc/init.d/rc.d/weavedWEB
chmod +x /etc/init.d/rc.d/weavedSCH
# on boot
ln -s /etc/init.d/rc.d/weavedSSH /etc/init.d/rc3.d/S700weavedSSH
ln -s /etc/init.d/rc.d/weavedRMT3 /etc/init.d/rc3.d/S700weavedRMT3
ln -s /etc/init.d/rc.d/weavedWEB /etc/init.d/rc3.d/S700weavedWEB
ln -s /etc/init.d/rc.d/weavedSCH /etc/init.d/rc3.d/S700weavedSCH

# now start them all up (we let registration do this)
#/etc/init.d/rc.d/weavedSSH start
#/etc/init.d/rc.d/weavedRMT3 start
#/etc/init.d/rc.d/weavedWEB start
#/etc/init.d/rc.d/weavedSCH start





