#!/bin/sh
# postrm script for connectd
#

TMP_DIR=/tmp

set -e
logger "connectd installer postrm state $1"
case "$1" in
  purge)
# remove global startup file
    if [ -f /usr/bin/connectdstart.sh ]; then
      rm -f /usr/bin/connectdstart.sh
    fi
# remove startup scripts	
    for file in /usr/bin/connectd*.sh ; do
      rm -f $file
    done
# remove notification scripts
    if [ -f /usr/bin/connectdnotify.sh ]; then
      rm -f /usr/bin/connectdnotify.sh
    fi
    for file in /usr/bin/notify_connectd*.sh ; do
      rm -f $file
    done
# remove configuration files
    for file in /etc/connectd/services/connectd*.conf ; do
      rm -f $file
    done
# remove PID files
    for file in /var/run/connectd*.pid ; do
      rm -f $file
    done
# remove installation template files
    if [ -d /usr/share/connectd ]; then
      rm -r /usr/share/connectd
    fi
# remove crontab entry
    crontab -l | grep -v connectdstart.sh | cat > $TMP_DIR/.crontmp
    crontab $TMP_DIR/.crontmp
    echo
    echo "If you uninstalled connectd without deleting Services first,"
    echo "there may be orphaned Services in your Service List.  Use the "
    echo "'Settings' link in the web portal Service List to delete these."
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    if [ -d /usr/share/connectd ]; then
      rm -r /usr/share/connectd
    fi
  ;;

  upgrade)
    echo "postrm called with upgrade" > /dev/null
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

exit 0
