#!/bin/sh
# postinst script for connectd
# https://remot3.it

set -e

logger "connectd installer postinst $1"
 
case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    configure|upgrade)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac
echo
echo "================================================================================"
echo
echo "================================================================================"
