#!/bin/sh
# postrm script for connectd
#

set -e
logger "connectd installer prerm $1"

case "$1" in

    remove|purge|deconfigure)
# remove serial number (HWID) file
    if [ -e /etc/connectd/serial.txt ]; then
      rm /etc/connectd/serial.txt
    fi
  ;;

    upgrade|failed-upgrade)
  ;;

    upgrade)
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

exit 0

