#!/bin/sh
# postinst script for weavedconnectd
#

set -e

logger "Weaved installer postinst $1"
 
case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    configure|upgrade)
    if [ -f /usr/bin/weavedstart.sh ]; then
# need to handle rename of launchschannel in previous versions to weavedschannel
	sed s/launchschannel/weavedschannel/ < /usr/bin/weavedstart.sh > /tmp/weavedstart.sh
	mv /tmp/weavedstart.sh /usr/bin
	chmod +x /usr/bin/weavedstart.sh
        logger "Restarting Weaved daemons"
	weavedstart.sh    
    fi
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac
echo
echo "================================================================================"
echo
echo "Run sudo weavedinstaller to interactively add remot3.it connection services."
echo
echo "================================================================================"
echo "If you are adding Weaved services with minimal interaction:"
echo "Copy and edit /usr/bin/remot3it_register to add account credentials"
echo "and definitions of services you wish to install."
echo
echo "Finally, run sudo remot3it_register to add remot3.it remote connection services."
echo
echo "See additional information in the remot3it_register script."
echo
