#!/bin/bash
# script to fix permissions after checking out of Github
DIR=weavedconnectd_1.3-07
chmod 644 $DIR/DEBIAN/control
chown root:root $DIR/DEBIAN/control
chown root:root $DIR/DEBIAN/conffiles
chmod 755 $DIR/DEBIAN/prerm
chown root:root $DIR/DEBIAN/prerm
chmod 755 $DIR/DEBIAN/postinst
chown root:root $DIR/DEBIAN/postinst
chmod 755 $DIR/DEBIAN/postrm
chown root:root $DIR/DEBIAN/postrm

chown root:root $DIR/etc
chown root:root $DIR/etc/weaved
chown root:root $DIR/etc/weaved/schannel.conf
chown root:root $DIR/usr
chown root:root $DIR/usr/bin
chown root:root $DIR/usr/bin/*
chown root:root $DIR/usr/share
chown root:root $DIR/usr/share/weavedconnectd
chown root:root $DIR/usr/share/weavedconnectd/conf
chown root:root $DIR/usr/share/weavedconnectd/conf/*.*
chown root:root $DIR/usr/share/weavedconnectd/cron
chown root:root $DIR/usr/share/weavedconnectd/cron/*.*
chown root:root $DIR/usr/share/weavedconnectd/scripts
chown root:root $DIR/usr/share/weavedconnectd/scripts/*
chown root:root $DIR/usr/share/weavedconnectd/scripts/*.*
chown root:root $DIR/usr/share/doc
chown root:root $DIR/usr/share/doc/weavedconnectd
chown root:root $DIR/usr/share/doc/weavedconnectd/*
chown root:root $DIR/usr/share/doc/weavedconnectd/*.*
chmod +x $DIR/usr/bin/*
